### PR TITLE
Update for Beatsaber 1.13.2

### PR DESCRIPTION
**Pull request by michael-r-elp**
Updated the Libraries for Beatsaber 1.13.2, I know this here isn't the current version, but at least this works for the current Beat Saber version, I think the other version always caused a crash for me.

### CODE REVIEW

**Comment by michael-r-elp** [comment]
Test version of the mod 
[Clockmod.zip](https://github.com/ChillGunner/ClockMod/files/5903896/Clockmod.zip)

**Comment by Jkryv3nchuk** [comment]
> Test version of the mod
> [Clockmod.zip](https://github.com/ChillGunner/ClockMod/files/5903896/Clockmod.zip)

I've been using it for the last few days and haven't come across any issues!
If its possible are you able to add in a 12 hour clock toggle?

**Comment by michael-r-elp** [comment]
> > Test version of the mod
> > [Clockmod.zip](https://github.com/ChillGunner/ClockMod/files/5903896/Clockmod.zip)
> 
> I've been using it for the last few days and haven't come across any issues!
> If its possible are you able to add in a 12 hour clock toggle?

Well, I would maybe look into that, but it would sure be easier if the full updated source code was posted by the creator, and I would also need their permission, and maybe he'll update it himself eventually, I haven't seen him anywhere on the Beat Saber Discords so far I think.

**Comment by michael-r-elp** [comment]
I have added all the important functions and settings now.

Current Version:
Forked over on: https://github.com/EnderdracheLP/ClockMod/releases

**Pull request merged**
